# -*- mode: ruby -*-
# vi: set ft=ruby :
# the first two lines are modeling for vim or emacs in case you are using them
# read more : https://vim.fandom.com/wiki/Modeline_magic and http://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html

# master config
MASTER_NODE_NAME = 'aallaliS'
MASTER_NODE_IP = '192.168.42.110'

#agent config
WORKER_NODE_NAME = 'aallaliSW'
WORKER_NODE_IP = '192.168.42.111'

# common config
MEM = 1024
CPU = 1
BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
BOX_AUTO_UPDATE = false

# disable firewall so we can have direct ssh access without need to copy our ssh public key to the machine 
# !!! (NOT RECOMMENDED , USE THE SSH KEYS METHOD IN PRODUCTION ENV, THIS IS ONLY FOR SCHOOL PRACTICING PURPOSE ) !!!
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_url = BOX_URL
	config.vm.box_check_update = BOX_AUTO_UPDATE
	config.vbguest.installer_options = { allow_kernel_upgrade: true }
	config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 

	# cancel install of vagrant-vbguest if exits , since versions +0.21 of vbguest plugin have this issue of re-download the plugin each time you `vagrant up`
	# if Vagrant.has_plugin?("vagrant-vbguest")
	#   config.vbguest.auto_update = false
	# end
  
	config.vm.provider "virtualbox" do |v|
		v.memory = MEM
		v.cpus = CPU
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define MASTER_NODE_NAME do |master|
		master.vm.hostname = MASTER_NODE_NAME
		master.vm.network :private_network, ip: MASTER_NODE_IP
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: "scripts/master_node_setup.sh", args: [MASTER_NODE_IP]

		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NODE_NAME
			# v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
		end
	end

	config.vm.define WORKER_NODE_NAME do |worker|
		worker.vm.hostname = WORKER_NODE_NAME
		worker.vm.network :private_network, ip: WORKER_NODE_IP 
		worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		worker.vm.provision "shell", privileged: true, path: "scripts/worker_node_setup.sh", args: [MASTER_NODE_IP, WORKER_NODE_IP]

		worker.vm.provider "virtualbox" do |v|
			v.name = WORKER_NODE_NAME
			# v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
		end
	end
end